"""Add role to telegram_subscribers

Revision ID: 0c2d9197d49d
Revises: d9e0f1a2b3c4
Create Date: 2026-02-09 06:17:36.968973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '0c2d9197d49d'
down_revision: Union[str, None] = 'd9e0f1a2b3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_anon_id'), table_name='events')
    op.drop_index(op.f('ix_events_quiz_run_id'), table_name='events')
    op.drop_index(op.f('ix_events_recommendation_run_id'), table_name='events')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_recommendation_runs_quiz_run_id'), table_name='recommendation_runs')
    op.drop_table('recommendation_runs')
    op.drop_index(op.f('ix_quiz_runs_anon_id'), table_name='quiz_runs')
    op.drop_index(op.f('ix_quiz_runs_user_id'), table_name='quiz_runs')
    op.drop_table('quiz_runs')
    op.drop_constraint(op.f('uq_oauth_accounts_provider_provider_user_id'), 'oauth_accounts', type_='unique')
    op.create_unique_constraint('uq_oauth_provider_user', 'oauth_accounts', ['provider', 'provider_user_id'])
    
    # Missing column in parsing_sources
    op.add_column('parsing_sources', sa.Column('status', sa.String(), server_default='waiting', nullable=False))
    op.create_index(op.f('ix_parsing_sources_status'), 'parsing_sources', ['status'], unique=False)
    
    # Missing table parsing_runs
    op.create_table(
        'parsing_runs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('source_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('items_scraped', sa.Integer(), server_default='0', nullable=False),
        sa.Column('items_new', sa.Integer(), server_default='0', nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('duration_seconds', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['source_id'], ['parsing_sources.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsing_runs_source_id'), 'parsing_runs', ['source_id'], unique=False)

    op.alter_column('product_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               nullable=False)
    op.drop_index(op.f('ix_product_embeddings_embedding'), table_name='product_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.add_column('telegram_subscribers', sa.Column('role', sa.String(), server_default='user', nullable=False))
    op.add_column('telegram_subscribers', sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_subscribers', 'permissions')
    op.drop_column('telegram_subscribers', 'role')
    op.create_index(op.f('ix_product_embeddings_embedding'), 'product_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('product_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               nullable=True)
    op.drop_constraint('uq_oauth_provider_user', 'oauth_accounts', type_='unique')
    op.drop_table('parsing_runs')
    op.drop_index(op.f('ix_parsing_sources_status'), table_name='parsing_sources')
    op.drop_column('parsing_sources', 'status')
    op.create_unique_constraint(op.f('uq_oauth_accounts_provider_provider_user_id'), 'oauth_accounts', ['provider', 'provider_user_id'], postgresql_nulls_not_distinct=False)
    op.create_table('quiz_runs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('anon_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('answers_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_quiz_runs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_runs'))
    )
    op.create_index(op.f('ix_quiz_runs_user_id'), 'quiz_runs', ['user_id'], unique=False)
    op.create_index(op.f('ix_quiz_runs_anon_id'), 'quiz_runs', ['anon_id'], unique=False)
    op.create_table('recommendation_runs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quiz_run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('engine_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('featured_gift_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gift_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('debug_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quiz_run_id'], ['quiz_runs.id'], name=op.f('fk_recommendation_runs_quiz_run_id_quiz_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_runs'))
    )
    op.create_index(op.f('ix_recommendation_runs_quiz_run_id'), 'recommendation_runs', ['quiz_run_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('anon_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quiz_run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('recommendation_run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('gift_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quiz_run_id'], ['quiz_runs.id'], name=op.f('fk_events_quiz_run_id_quiz_runs')),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], name=op.f('fk_events_recommendation_run_id_recommendation_runs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_index(op.f('ix_events_recommendation_run_id'), 'events', ['recommendation_run_id'], unique=False)
    op.create_index(op.f('ix_events_quiz_run_id'), 'events', ['quiz_run_id'], unique=False)
    op.create_index(op.f('ix_events_anon_id'), 'events', ['anon_id'], unique=False)
    # ### end Alembic commands ###
