"""add_hypotheses_table

Revision ID: 0ee809d48059
Revises: 345ee831ac2a
Create Date: 2026-02-13 18:23:45.010409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ee809d48059'
down_revision: Union[str, None] = '345ee831ac2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hypotheses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=True),
    sa.Column('track_title', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('user_reaction', sa.String(), nullable=True),
    sa.Column('is_shown', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], name=op.f('fk_hypotheses_recipient_id_recipients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hypotheses'))
    )
    op.create_index(op.f('ix_hypotheses_recipient_id'), 'hypotheses', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_hypotheses_session_id'), 'hypotheses', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hypotheses_session_id'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_recipient_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    # ### end Alembic commands ###
