"""add_search_queries_to_hypotheses

Revision ID: 48521be6e237
Revises: 0ee809d48059
Create Date: 2026-02-13 18:26:29.944771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48521be6e237'
down_revision: Union[str, None] = '0ee809d48059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hypotheses', sa.Column('search_queries', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hypotheses', 'search_queries')
    # ### end Alembic commands ###
