"""Add llm_gift_vector

Revision ID: 67f5a0418824
Revises: 0005_llm_scoring
Create Date: 2026-01-23 07:04:16.638635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67f5a0418824'
down_revision: Union[str, None] = '0005_llm_scoring'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('llm_gift_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'llm_gift_vector')
    # ### end Alembic commands ###
