"""Add llm_gift_vector

Revision ID: 67f5a0418824
Revises: 0005_llm_scoring
Create Date: 2026-01-23 07:04:16.638635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67f5a0418824'
down_revision: Union[str, None] = '0005_llm_scoring'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_runs_anon_id'), table_name='quiz_runs')
    op.drop_index(op.f('ix_quiz_runs_user_id'), table_name='quiz_runs')
    op.drop_table('quiz_runs')
    op.drop_index(op.f('ix_events_anon_id'), table_name='events')
    op.drop_index(op.f('ix_events_quiz_run_id'), table_name='events')
    op.drop_index(op.f('ix_events_recommendation_run_id'), table_name='events')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('visitors')
    op.drop_index(op.f('ix_recommendation_runs_quiz_run_id'), table_name='recommendation_runs')
    op.drop_table('recommendation_runs')
    op.drop_constraint(op.f('uq_oauth_accounts_provider_provider_user_id'), 'oauth_accounts', type_='unique')
    op.create_unique_constraint('uq_oauth_provider_user', 'oauth_accounts', ['provider', 'provider_user_id'])
    op.alter_column('product_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               nullable=False)
    op.drop_index(op.f('ix_product_embeddings_embedding'), table_name='product_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.add_column('products', sa.Column('llm_gift_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'llm_gift_vector')
    op.create_index(op.f('ix_product_embeddings_embedding'), 'product_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('product_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               nullable=True)
    op.drop_constraint('uq_oauth_provider_user', 'oauth_accounts', type_='unique')
    op.create_unique_constraint(op.f('uq_oauth_accounts_provider_provider_user_id'), 'oauth_accounts', ['provider', 'provider_user_id'], postgresql_nulls_not_distinct=False)
    op.create_table('recommendation_runs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quiz_run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('engine_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('featured_gift_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gift_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('debug_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quiz_run_id'], ['quiz_runs.id'], name='fk_recommendation_runs_quiz_run_id_quiz_runs', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_recommendation_runs'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_recommendation_runs_quiz_run_id'), 'recommendation_runs', ['quiz_run_id'], unique=False)
    op.create_table('visitors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visitors'))
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('anon_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quiz_run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('recommendation_run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('gift_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quiz_run_id'], ['quiz_runs.id'], name=op.f('fk_events_quiz_run_id_quiz_runs')),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], name=op.f('fk_events_recommendation_run_id_recommendation_runs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_index(op.f('ix_events_recommendation_run_id'), 'events', ['recommendation_run_id'], unique=False)
    op.create_index(op.f('ix_events_quiz_run_id'), 'events', ['quiz_run_id'], unique=False)
    op.create_index(op.f('ix_events_anon_id'), 'events', ['anon_id'], unique=False)
    op.create_table('quiz_runs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('anon_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('answers_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_quiz_runs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_runs'))
    )
    op.create_index(op.f('ix_quiz_runs_user_id'), 'quiz_runs', ['user_id'], unique=False)
    op.create_index(op.f('ix_quiz_runs_anon_id'), 'quiz_runs', ['anon_id'], unique=False)
    # ### end Alembic commands ###
