"""add_compute_tasks_table

Revision ID: cf54215d5932
Revises: 7ae0d1a3c3ba
Create Date: 2026-02-16 19:29:42.359903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf54215d5932'
down_revision: Union[str, None] = '7ae0d1a3c3ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compute_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), server_default='low', nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compute_tasks'))
    )
    op.create_index(op.f('ix_compute_tasks_priority'), 'compute_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_compute_tasks_status'), 'compute_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_compute_tasks_task_type'), 'compute_tasks', ['task_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compute_tasks_task_type'), table_name='compute_tasks')
    op.drop_index(op.f('ix_compute_tasks_status'), table_name='compute_tasks')
    op.drop_index(op.f('ix_compute_tasks_priority'), table_name='compute_tasks')
    op.drop_table('compute_tasks')
    # ### end Alembic commands ###
