"""add llm logs table

Revision ID: d6308a1fcec9
Revises: 77b8e12855d2
Create Date: 2026-02-20 14:43:41.583119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6308a1fcec9'
down_revision: Union[str, None] = '77b8e12855d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('call_type', sa.String(), nullable=False),
    sa.Column('input_messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('output_content', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('hypothesis_id', sa.UUID(), nullable=True),
    sa.Column('experiment_id', sa.String(), nullable=True),
    sa.Column('variant_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_logs'))
    )
    op.create_index(op.f('ix_llm_logs_call_type'), 'llm_logs', ['call_type'], unique=False)
    op.create_index(op.f('ix_llm_logs_experiment_id'), 'llm_logs', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_llm_logs_hypothesis_id'), 'llm_logs', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_llm_logs_model'), 'llm_logs', ['model'], unique=False)
    op.create_index(op.f('ix_llm_logs_provider'), 'llm_logs', ['provider'], unique=False)
    op.create_index(op.f('ix_llm_logs_session_id'), 'llm_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_llm_logs_variant_id'), 'llm_logs', ['variant_id'], unique=False)
    op.add_column('search_logs', sa.Column('predicted_category', sa.String(), nullable=True))
    op.create_index(op.f('ix_search_logs_predicted_category'), 'search_logs', ['predicted_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_logs_predicted_category'), table_name='search_logs')
    op.drop_column('search_logs', 'predicted_category')
    op.drop_index(op.f('ix_llm_logs_variant_id'), table_name='llm_logs')
    op.drop_index(op.f('ix_llm_logs_session_id'), table_name='llm_logs')
    op.drop_index(op.f('ix_llm_logs_provider'), table_name='llm_logs')
    op.drop_index(op.f('ix_llm_logs_model'), table_name='llm_logs')
    op.drop_index(op.f('ix_llm_logs_hypothesis_id'), table_name='llm_logs')
    op.drop_index(op.f('ix_llm_logs_experiment_id'), table_name='llm_logs')
    op.drop_index(op.f('ix_llm_logs_call_type'), table_name='llm_logs')
    op.drop_table('llm_logs')
    # ### end Alembic commands ###
