"""add_weeek_accounts_table

Revision ID: e5895b01411f
Revises: 0c2d9197d49d
Create Date: 2026-02-09 09:10:46.954223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5895b01411f'
down_revision: Union[str, None] = '0c2d9197d49d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weeek_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('weeek_api_token', sa.String(), nullable=False),
    sa.Column('weeek_user_id', sa.String(), nullable=True),
    sa.Column('weeek_workspace_id', sa.Integer(), nullable=True),
    sa.Column('personal_project_id', sa.Integer(), nullable=True),
    sa.Column('personal_board_id', sa.Integer(), nullable=True),
    sa.Column('reminder_time', sa.String(), server_default='09:00', nullable=False),
    sa.Column('timezone', sa.String(), server_default='Europe/Moscow', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['telegram_chat_id'], ['telegram_subscribers.chat_id'], name=op.f('fk_weeek_accounts_telegram_chat_id_telegram_subscribers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weeek_accounts'))
    )
    op.create_index(op.f('ix_weeek_accounts_telegram_chat_id'), 'weeek_accounts', ['telegram_chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weeek_accounts_telegram_chat_id'), table_name='weeek_accounts')
    op.drop_table('weeek_accounts')
    # ### end Alembic commands ###
